server:
  port: 8088
spring:
  application:
    name: shms
  mail:
    host: 
    username: 
    password: 
    default-encoding: utf-8
  thymeleaf:
    cache: false # 关闭模板引擎缓存
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      driver-class-name: 
      url: 
      username: 
      password: 
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resourses/,classpath:/resourses/,classpath:/static/,classpath:/public/
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      insert_strategy: ignored

